### ISSUE TITLE
Logging of item creation to Cradle developer's cloud server (+JSONP execution?)

### ISSUE THREAD

**Issue by GreenReaper** [wbstack/cradle#4]
[An attempt seems to be made to log successful creation](https://github.com/wbstack/cradle/blob/main/public_html/vue_components/shex-page.html#L264) to https://tools.wmflabs.org/magnustools/logger.php, which redirects to https://magnustools.toolforge.org/logger.php. I initially thought it was sending the item data or schema, as an object is cached in `me.j` - but it looks like that isn't the case. The request operates as a [JSONP](https://en.wikipedia.org/wiki/JSONP) callback, though; so... maybe it can if it wants to?
> jQuery3310718887932706373_1618286345336({"status":"OK"})

This should probably be configurable; it may cause latency or errors, or violate third-party user's privacy expectations or policies. If a callback accesses non-free content or private information, it may violate the [Cloud Services Terms of Use](https://wikitech.wikimedia.org/wiki/Wikitech:Cloud_Services_Terms_of_use), and no warning is shown. Presumably if nothing else the referer header would be sent, identifying a domain using the tool. There's no notice in the README.

I think CSP should prevent this, if implemented, and NoScript appears to block it as well; but it seems like a bad idea to rely on that.

**Comment by addshore** [comment]
CSP should indeed be added

**Comment by lokal-profil** [comment]
Could https://github.com/wbstack/cradle/blob/e7f62d5b8b3a2df889071b8b888da32ad8636b3c/public_html/vue_components/subject-page.html#L185 just be dropped?

**Comment by deer-wmde** [comment]
moved https://phabricator.wikimedia.org/T357108
