### ISSUE TITLE
"Git", "Help" buttons go to the wrong places

### ISSUE THREAD

**Issue by GreenReaper** [wbstack/cradle#5]
A few small but niggly link issues in [the current state](https://furry.wiki.opencura.com/tools/cradle/?#/shex/E2) (which is, of course, experimental):
* "[Git](https://github.com/wbstack/cradle/blob/main/public_html/index.html#L30)" goes to [an old bitbucket](https://bitbucket.org/magnusmanske/wikidata-todo/src/master/public_html/cradle/), pointing to [a deleted one](https://bitbucket.org/magnusmanske/cradle/). Should probably go [here](https://github.com/magnusmanske/cradle) in upstream, possibly [here](https://github.com/wbstack/cradle) in this version.
* "[Help](https://github.com/wbstack/cradle/blob/main/public_html/index.html#L33)" is right except for some reason it's being [appended to the current path](https://furry.wiki.opencura.com/tools/cradle/https://furry.wiki.opencura.com/wiki/Project:Cradle) rather than replacing it, so it's a broken link. [Appears to be set here](https://github.com/wbstack/cradle/blob/e7f62d5b8b3a2df889071b8b888da32ad8636b3c/public_html/vue.js#L89) - added in [this commit](https://github.com/wbstack/cradle/commit/b2807ffb6704dc554ab02f032290498aeb53b22d#diff-dcc564bc94a21ff030f5d47703d44623ad0691a956acfad11a75f9e8fff649ef). To me, the JS seems odd; $1 is [usually used in the second parameter of a replace to refer to a capturing group in the first](https://stackoverflow.com/a/16137595/2283898) (and even if the parameters were swapped, I'm not sure there is such a group). Possibly related to use of the Wikidata API, resulting in autocomplete from there - might be trying to match the start of a different URL? Or just worked before because it was the root of the site, not a subdirectory?

The second makes it hard to point directly to Cradle as people can't get advice; it's also one of the first things likely to be clicked.

**Comment by deer-wmde** [comment]
moved https://phabricator.wikimedia.org/T357107
